const authTypes = {
  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_FAILED: "SIGNIN_FAILED",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",

  LOGOUT: "LOGOUT",
};

export default authTypes;
