const categoryTypes = {
  CREATE_CATEGORY_REQUEST: "CREATE_CATEGORY_REQUEST",
  CREATE_CATEGORY_FAILED: "CREATE_CATEGORY_FAILED",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",

  UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
  UPDATE_CATEGORY_FAILED: "UPDATE_CATEGORY_FAILED",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",

  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_FAILED: "DELETE_CATEGORY_FAILED",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",

  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_FAILED: "GET_CATEGORY_FAILED",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",

  GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
  GET_CATEGORIES_FAILED: "GET_CATEGORIES_FAILED",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",

  RESET_ERROR: "RESET_ERROR",
};

export default categoryTypes;
