const ordersTypes = {
  DELETE_ORDER_REQUEST: "DELETE_ORDER_REQUEST",
  DELETE_ORDER_FAILED: "DELETE_ORDER_FAILED",
  DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",

  UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
  UPDATE_ORDER_FAILED: "UPDATE_ORDER_FAILED",
  UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",

  UPDATE_PEYMENT_REQUEST: "UPDATE_PEYMENT_REQUEST",
  UPDATE_PEYMENT_FAILED: "UPDATE_PEYMENT_FAILED",
  UPDATE_PEYMENT_SUCCESS: "UPDATE_PEYMENT_SUCCESS",

  GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
  GET_ORDER_FAILED: "GET_ORDER_FAILED",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",

  GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
  GET_ORDERS_FAILED: "GET_ORDERS_FAILED",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",

  RESET_ERROR: "RESET_ERROR",
};

export default ordersTypes;
