const productsTypes = {
  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_FAILED: "CREATE_PRODUCT_FAILED",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",

  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_FAILED: "DELETE_PRODUCT_FAILED",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",

  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_FAILED: "UPDATE_PRODUCT_FAILED",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",

  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_FAILED: "GET_PRODUCT_FAILED",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",

  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_FAILED: "GET_PRODUCTS_FAILED",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",

  RESET_ERROR: "RESET_ERROR",
};

export default productsTypes;
